---
- name: register splunk repo
  stat:
    path: /etc/yum.repos.d/splunk.repo
  register: splunk_repo

- name: add a local splunk repository
  become: true
  yum_repository:
    reposdir: /etc/yum.repos.d
    name: splunk-repo
    description: Splunk
    file: splunk
    baseurl: file:///vagrant/repo
    gpgcheck: no
    enabled: yes
