---
- name: install base packages
  become: true
  yum:
    name: "{{ item }}"
    state: installed
    update_cache: yes
  with_items:
    - nano
    - createrepo
  when: ansible_system == "Linux"

- name: register repodata
  stat:
    path: repo/repodata/repomd.xml
  register: repodata
  when: ansible_system == "Linux"

- name: register repodata mtime
  debug:
    msg: "{{ repodata.stat.mtime|int }}"
  register: repodata_mtime
  when: ansible_system == "Linux" and repodata.stat.exists == True

- name: register current time
  debug:
    msg: "{{ ansible_date_time.epoch|int-86400 }}"
  register: current_time
  when: ansible_system == "Linux" and repodata.stat.exists == True

- name: create splunk repo
  become: true
  command: createrepo /vagrant/repo/
  when: (current_time > repodata_mtime and ansible_system == "Linux") or (ansible_system == "Linux" and repodata.stat.exists == False)

- name: register splunk repo
  stat:
    path: /etc/yum.repos.d/splunk.repo
  register: splunk_repo

- name: add a local splunk repository
  become: true
  yum_repository:
    reposdir: /etc/yum.repos.d
    name: splunk-repo
    description: Splunk
    file: splunk
    baseurl: file:///vagrant/repo
    gpgcheck: no
    enabled: yes
